'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const QRCode = require('qrcode');

const Util = require('./Util');
const ServerError = require('./ServerError');
const MASKING_PRESETS = require('./MaskingPresets');

const {
  AWG_PROTOCOL_VERSION,
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_DEFAULT_ADDRESS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ALLOWED_IPS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
  JC,
  JMIN,
  JMAX,
  S1,
  S2,
  S3,
  S4,
  H1,
  H2,
  H3,
  H4,
  I1,
  I2,
  I3,
  I4,
  I5,
  HEADER_PROTECTION_KEY,
  CONTENT_PADDING_ADDITION,
  REKEY_AFTER_TIME,
  REKEY_TIMEOUT,
  REJECT_AFTER_TIME,
  KEEPALIVE_TIMEOUT,
  MAX_HANDSHAKE_ATTEMPTS,
  RANDOM_TRAILERS,
  DISABLE_COOKIES,
} = require('../config');

module.exports = class WireGuard {

  async getConfig() {
    if (!this.__configPromise) {
      this.__configPromise = Promise.resolve().then(async () => {
        if (!WG_HOST) {
          throw new Error('WG_HOST Environment Variable Not Set!');
        }

        debug('Loading configuration...');
        let config;
        try {
          config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
          config = JSON.parse(config);
          debug('Configuration loaded.');
        } catch (err) {
          const privateKey = await Util.exec('wg genkey');
          const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
            log: 'echo ***hidden*** | wg pubkey',
          });

          const address = WG_DEFAULT_ADDRESS.replace('x', '1');

          config = {
            server: {
              privateKey,
              publicKey,
              address,
              jc: JC,
              jmin: JMIN,
              jmax: JMAX,
              s1: S1,
              s2: S2,
              h1: H1,
              h2: H2,
              h3: H3,
              h4: H4,
            },
            clients: {},
          };

          debug('Configuration generated.');
        }

        this.#ensureProtocolConfig(config);
        await this.__saveConfig(config);
        await Util.exec('wg-quick down wg0').catch(() => { });
        await Util.exec('wg-quick up wg0').catch((err) => {
          if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
            throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
          }

          throw err;
        });
        // await Util.exec(`iptables -t nat -A POSTROUTING -s ${WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ' + WG_DEVICE + ' -j MASQUERADE`);
        // await Util.exec('iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT');
        // await Util.exec('iptables -A FORWARD -i wg0 -j ACCEPT');
        // await Util.exec('iptables -A FORWARD -o wg0 -j ACCEPT');
        await this.__syncConfig();

        return config;
      });
    }

    return this.__configPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    await this.__saveConfig(config);
    await this.__syncConfig();
  }

  async __saveConfig(config) {
    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = ${WG_PORT}
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
Jc = ${config.server.jc}
Jmin = ${config.server.jmin}
Jmax = ${config.server.jmax}
S1 = ${config.server.s1}
S2 = ${config.server.s2}
H1 = ${config.server.h1}
H2 = ${config.server.h2}
H3 = ${config.server.h3}
H4 = ${config.server.h4}
${this.#isAwg31Config(config) ? `S3 = ${config.server.s3}
S4 = ${config.server.s4}
HeaderProtectionKey = ${config.server.headerProtectionKey}
ContentPaddingAddition = ${config.server.contentPaddingAddition}
RekeyAfterTime = ${config.server.rekeyAfterTime}
RekeyTimeout = ${config.server.rekeyTimeout}
RejectAfterTime = ${config.server.rejectAfterTime}
KeepaliveTimeout = ${config.server.keepaliveTimeout}
MaxHandshakeAttempts = ${config.server.maxHandshakeAttempts}
RandomTrailers = ${config.server.randomTrailers}
DisableCookies = ${config.server.disableCookies}
` : ''}\
`;

    for (const [clientId, client] of Object.entries(config.clients)) {
      if (!client.enabled) continue;

      result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
    }

    debug('Config saving...');
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await Util.exec('wg syncconf wg0 <(wg-quick strip wg0)');
    debug('Config synced.');
  }

  async getClients() {
    const config = await this.getConfig();
    const clients = Object.entries(config.clients).map(([clientId, client]) => ({
      id: clientId,
      name: client.name,
      enabled: client.enabled,
      address: client.address,
      publicKey: client.publicKey,
      createdAt: new Date(client.createdAt),
      updatedAt: new Date(client.updatedAt),
      allowedIPs: client.allowedIPs,
      downloadableConfig: 'privateKey' in client,
      persistentKeepalive: null,
      latestHandshakeAt: null,
      transferRx: null,
      transferTx: null,
    }));

    // Loop WireGuard status
    const dump = await Util.exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint, // eslint-disable-line no-unused-vars
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const client = clients.find((client) => client.publicKey === publicKey);
        if (!client) return;

        client.latestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));
        client.transferRx = Number(transferRx);
        client.transferTx = Number(transferTx);
        client.persistentKeepalive = persistentKeepalive;
      });

    return clients;
  }

  async getClient({ clientId }) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) {
      throw new ServerError(`Client Not Found: ${clientId}`, 404);
    }

    return client;
  }

  async getClientConfiguration({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getClient({ clientId });
    const masking = {
      h1: config.server.h1,
      h2: config.server.h2,
      h3: config.server.h3,
      h4: config.server.h4,
      s3: config.server.s3,
      s4: config.server.s4,
      headerProtectionKey: config.server.headerProtectionKey,
      contentPaddingAddition: config.server.contentPaddingAddition,
      rekeyAfterTime: config.server.rekeyAfterTime,
      rekeyTimeout: config.server.rekeyTimeout,
      rejectAfterTime: config.server.rejectAfterTime,
      keepaliveTimeout: config.server.keepaliveTimeout,
      maxHandshakeAttempts: config.server.maxHandshakeAttempts,
      randomTrailers: config.server.randomTrailers,
      disableCookies: config.server.disableCookies,
      i1: I1,
      i2: I2,
      i3: I3,
      i4: I4,
      i5: I5,
      ...client.masking,
    };

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ''}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ''}\

# --- Транспортная маскировка ---
# Jc: количество мусорных пакетов перед каждым handshake.
Jc = ${config.server.jc}
# Jmin/Jmax: минимальный и максимальный размер мусорного пакета в байтах.
# Это размеры пакетов, а не задержка в миллисекундах.
Jmin = ${config.server.jmin}
Jmax = ${config.server.jmax}
# S1/S2: случайное дополнение пакетов инициализации и ответа handshake.
S1 = ${config.server.s1}
S2 = ${config.server.s2}
${this.#isAwg31Config(config) ? `S3 = ${masking.s3}
S4 = ${masking.s4}
` : ''}\

# --- Динамические заголовки пакетов ---
# H1-H4: значения или диапазоны заголовков Init, Response, Cookie и Transport.
# Значения и диапазоны H1-H4 внутри конфигурации не должны пересекаться.
H1 = ${masking.h1}
H2 = ${masking.h2}
H3 = ${masking.h3}
H4 = ${masking.h4}
${this.#isAwg31Config(config) ? `
# --- AmneziaWG 3.1 ---
# HeaderProtectionKey должен совпадать на сервере и клиенте.
HeaderProtectionKey = ${masking.headerProtectionKey}
ContentPaddingAddition = ${masking.contentPaddingAddition}
RekeyAfterTime = ${masking.rekeyAfterTime}
RekeyTimeout = ${masking.rekeyTimeout}
RejectAfterTime = ${masking.rejectAfterTime}
KeepaliveTimeout = ${masking.keepaliveTimeout}
MaxHandshakeAttempts = ${masking.maxHandshakeAttempts}
RandomTrailers = ${masking.randomTrailers}
DisableCookies = ${masking.disableCookies}
` : ''}\

# --- Маскировочные CPS-пакеты ---
# I1-I5 отправляются по порядку перед реальным WireGuard handshake.
# <b 0x...> добавляет статические байты, <r N> — N случайных байтов.
# Значения ниже имитируют начало TLS/QUIC-подобного UDP-обмена.
I1 = ${masking.i1}
I2 = ${masking.i2}
I3 = ${masking.i3}
I4 = ${masking.i4}
I5 = ${masking.i5}

${masking.initPacketDelay === undefined ? '' : `Init_Packet_Delay = ${masking.initPacketDelay}\n`}
[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_PORT}`;
  }

  async getClientQRCodeSVG({ clientId }) {
    const config = await this.getClientConfiguration({ clientId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
      errorCorrectionLevel: 'L',
    });
  }

  async createClient({ name, maskingPreset, masking }) {
    if (!name) {
      throw new Error('Missing: Name');
    }

    const normalizedMasking = this.#normalizeMasking({ maskingPreset, masking });
    const config = await this.getConfig();

    const privateKey = await Util.exec('wg genkey');
    const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`);
    const preSharedKey = await Util.exec('wg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const client = Object.values(config.clients).find((client) => {
        return client.address === WG_DEFAULT_ADDRESS.replace('x', i);
      });

      if (!client) {
        address = WG_DEFAULT_ADDRESS.replace('x', i);
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of clients reached.');
    }

    // Create Client
    const id = crypto.randomUUID();
    const client = {
      id,
      name,
      address,
      privateKey,
      publicKey,
      preSharedKey,

      createdAt: new Date(),
      updatedAt: new Date(),

      enabled: true,
      ...(normalizedMasking ? { masking: normalizedMasking } : {}),
    };

    config.clients[id] = client;

    await this.saveConfig();

    return client;
  }

  getMaskingPresets() {
    return MASKING_PRESETS;
  }

  #ensureProtocolConfig(config) {
    const persistedAwg31 = config.server.awgProtocolVersion === '3.1';
    if (AWG_PROTOCOL_VERSION !== '3.1' && !persistedAwg31) return;

    config.server.awgProtocolVersion = '3.1';
    if (!persistedAwg31) {
      config.server.h1 = H1;
      config.server.h2 = H2;
      config.server.h3 = H3;
      config.server.h4 = H4;
    }
    config.server.s3 = config.server.s3 || S3;
    config.server.s4 = config.server.s4 || S4;
    config.server.headerProtectionKey = config.server.headerProtectionKey
      || HEADER_PROTECTION_KEY
      || crypto.randomBytes(32).toString('base64');
    config.server.contentPaddingAddition = config.server.contentPaddingAddition || CONTENT_PADDING_ADDITION;
    config.server.rekeyAfterTime = config.server.rekeyAfterTime || REKEY_AFTER_TIME;
    config.server.rekeyTimeout = config.server.rekeyTimeout || REKEY_TIMEOUT;
    config.server.rejectAfterTime = config.server.rejectAfterTime || REJECT_AFTER_TIME;
    config.server.keepaliveTimeout = config.server.keepaliveTimeout || KEEPALIVE_TIMEOUT;
    config.server.maxHandshakeAttempts = config.server.maxHandshakeAttempts || MAX_HANDSHAKE_ATTEMPTS;
    config.server.randomTrailers = config.server.randomTrailers || RANDOM_TRAILERS;
    config.server.disableCookies = config.server.disableCookies || DISABLE_COOKIES;
  }

  #isAwg31Config(config) {
    return AWG_PROTOCOL_VERSION === '3.1' || config.server.awgProtocolVersion === '3.1';
  }

  #normalizeMasking({ maskingPreset, masking }) {
    if (!maskingPreset && !masking) return null;

    const preset = maskingPreset
      ? MASKING_PRESETS.find((item) => item.id === maskingPreset)
      : null;
    if (maskingPreset && !preset) {
      throw new ServerError(`Unknown masking preset: ${maskingPreset}`, 400);
    }
    if (masking !== undefined && (masking === null || typeof masking !== 'object' || Array.isArray(masking))) {
      throw new ServerError('Invalid masking configuration', 400);
    }

    const source = { ...(preset || {}), ...(masking || {}) };
    const result = {};
    const headerPattern = /^\d+(?:-\d+)?$/;
    const packetPattern = /^(?:\s*<(?:b 0x[0-9a-fA-F]+|r \d+)>\s*)+$/;

    for (const key of ['h1', 'h2', 'h3', 'h4']) {
      if (source[key] === undefined || source[key] === '') continue;
      const value = String(source[key]).trim();
      if (!headerPattern.test(value)) {
        throw new ServerError(`Invalid ${key.toUpperCase()}`, 400);
      }
      result[key] = value;
    }

    for (const key of ['i1', 'i2', 'i3', 'i4', 'i5']) {
      if (source[key] === undefined || source[key] === '') continue;
      const value = String(source[key]).trim();
      if (!packetPattern.test(value)) {
        throw new ServerError(`Invalid ${key.toUpperCase()}`, 400);
      }
      result[key] = value;
    }

    if (source.initPacketDelay !== undefined && source.initPacketDelay !== '') {
      const delay = Number(source.initPacketDelay);
      if (!Number.isInteger(delay) || delay < 0) {
        throw new ServerError('Invalid Init_Packet_Delay', 400);
      }
      result.initPacketDelay = delay;
    }

    return Object.keys(result).length ? result : null;
  }

  async deleteClient({ clientId }) {
    const config = await this.getConfig();

    if (config.clients[clientId]) {
      delete config.clients[clientId];
      await this.saveConfig();
    }
  }

  async enableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = true;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async disableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = false;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientName({ clientId, name }) {
    const client = await this.getClient({ clientId });

    client.name = name;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientAddress({ clientId, address }) {
    const client = await this.getClient({ clientId });

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    client.address = address;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('wg-quick down wg0').catch(() => { });
  }

};
